# dynamixel goal velocity
GOAL_VELOCITY: 10

# deformation
DEFORMATION_TH: 5.0

# deformation
OCCLUSION_TH: 4.0

# hsv param: hand
H_MIN_HAND: 80
H_MAX_HAND: 179
S_MIN_HAND: 0
S_MAX_HAND: 225
V_MIN_HAND: 170
V_MAX_HAND: 255

# hsv param: obj
H_MIN_OBJ: 0
H_MAX_OBJ: 20
S_MIN_OBJ: 140
S_MAX_OBJ: 255
V_MIN_OBJ: 50
V_MAX_OBJ: 255